app.py
from flask import Flask, render_template
from models.kinase.views import kinase_blueprint
from models.inhibitor.views import inhibitor_blueprint
from models.analysis.views import analysis_blueprint


APP = Flask(__name__)
APP.config.from_object('config')

@APP.route("/")
def index():

    """ Description: Home Route that renders the index template        """
    return render_template('index.html')

APP.register_blueprint(kinase_blueprint, url_prefix="/kinase")
APP.register_blueprint(inhibitor_blueprint, url_prefix="/inhibitor")
APP.register_blueprint(analysis_blueprint, url_prefix="/analysis")

models/analysis/views.py
"""This file is to run the essential functions of the analysis site """
import os

import zipfile
from flask import Blueprint, render_template, request, url_for, redirect, send_file
from werkzeug.utils import secure_filename
import config
from models.analysis import process_file
import matplotlib as mat
mat.use('agg')

__author__ = "Ildiko"

analysis_blueprint = Blueprint('analysis', __name__) #bluprint to wrap up the code

#contains abs path to uploaded file
UPLOAD_FOLDER = config.UPLOAD_FOLDER
#the folder where the results can be saved-the full csv
DOWNLOAD_FOLDER = config.DOWNLOAD_FOLDER

ALLOWED_EXTENSIONS = {'tsv'} #specify the file extension allowed
def allowed_file(filename):
        """ allowed extensions to upload"""
        return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@analysis_blueprint.route('/', methods=['POST', 'GET'])
def index():
    """ Main site of analysis with the form"""
    return render_template("analysis/index.html")

@analysis_blueprint.route('upload/', methods=['POST', 'GET'])
def upload():
    """This function uploads the file to the uploads folder """
    if request.method == 'POST':
        uploadedfile = None
        file = request.files['file']
        # if file sent save it to upload_folder and redirect to analysis:
        for file in request.files.getlist('file'):
            uploadedfile = secure_filename(file.filename)
            file.save(os.path.join(UPLOAD_FOLDER, uploadedfile))
            return redirect(url_for('analysis.uploaded', uploadedfile=uploadedfile))
    return render_template("analysis/index.html")

@analysis_blueprint.route('uploaded/', methods=['GET', 'POST'])
def uploaded():
    """This function runs the analysis and returns the results """
    result_object = process_file.actual_analysis() #all file processing function runs from process_file.py
    ourprecious = process_file.create_fancybargraph(result_object) # graphical representation of the results 
    return render_template("analysis/results.html",
                           tables=[result_object.to_html(classes='data', header="true")],
                           ourprecious=ourprecious)
 
@analysis_blueprint.route('/dowload_all', methods=['GET', 'POST'])
def download_all():
    """This is the function which dowloads the results for the user"""

    zipf = zipfile.ZipFile('Results.zip','w', zipfile.ZIP_DEFLATED) #create zipfile with all related result files
    for root, dirs, files in os.walk('downloads/'):
        for file in files:
            zipf.write('downloads/'+file)
    zipf.close()
    return send_file('Results.zip',
                     mimetype='zip',
                     attachment_filename='Results.zip',
                     as_attachment=True)

models/inhibitor/views.py
# import flask, blueprint, render template, request, url and redirect from flask
from flask import Flask, Blueprint, render_template, request,  url_for, redirect
# import database from common file 
import common.database as db

# name inhibitor blueprint route 
inhibitor_blueprint= Blueprint('inhibitor', __name__)
@inhibitor_blueprint.route('/', methods=['GET','POST'])
def index():      
    if request.method == 'POST':
        if request.form['name']:

            # give a variable for user input 
            nameFilter = request.form['name']

            # make nameFilter uppercase to match names in database 
            nameFilter = nameFilter.upper()

        return redirect(url_for('inhibitor.results', nameFilter=nameFilter))
    return render_template('inhibitor/index.html')

# create route for reuslts page that takes nameFilter as parameter 
@inhibitor_blueprint.route('/results/<nameFilter>')
def results(nameFilter):
    # try:
    # query the database for inhibitor information inhibitor table 
    query = 'SELECT * FROM public."Inhibitor_table" WHERE "INHIBITOR_NAME" = \'' + nameFilter + '\''
    data = db.Query(query)
    return render_template('inhibitor/results.html', data=data) 
    # except:
    #     return "Sorry! No information available for that kinase!"

models/kinase/views.py
# import flask, blueprint, render template, request, url and redirect from flask
from flask import Flask, Blueprint, render_template, request,  url_for, redirect
# import database from common database 
import common.database as db

# name kinase blueprint
kinase_blueprint = Blueprint('kinase', __name__)

# make search box using request form
@kinase_blueprint.route('/', methods=['GET', 'POST'])
def index():       
    if request.method == 'POST':
        if request.form['name']:
            # make user input a variable named nameFilter
            nameFilter = request.form['name']
            # turn kinase name into uppercase 
            nameFilter = nameFilter.upper()
        # redirect to results page
        return redirect(url_for('kinase.results', nameFilter=str(nameFilter)))
    return render_template('kinase/index.html')

# make a results route that takes nameFilter as parameter 
@kinase_blueprint.route('/results/<nameFilter>')
def results(nameFilter):
    #try:
    #query = db.Query(query)
    #if nameFilter in query:
        # set kinase query 
    query =  'SELECT * FROM public."Kinase_table" WHERE "CAP_KINASE_NAME" LIKE \'' "%" + nameFilter +  "%" '\' OR "SYNONYMS" LIKE  \'' "%" + nameFilter +  "%" '\''
    # gather data from database 
    data = db.Query(query)
    # set query for inhibitor nae 
    inhibitor = 'SELECT "INHIBITOR_NAME" FROM public."KiInh_relation_table" WHERE "KINASE_NAME" LIKE \'' "%" + nameFilter +  "%" '\''
    data2 = db.Inhibitor(inhibitor)
    # set query for phosphosites on target genes
    phosphosite = 'SELECT * FROM public."Phosphosite_table" WHERE "KINASE_NAME" LIKE \''"%" + nameFilter +  "%" '\' OR "SYNONYMS" LIKE  \'' "%" + nameFilter +  "%" '\''
    data3 = db.Phospho(phosphosite)
    # set query for phosphosites on selected kinase
    phosphosite = 'SELECT * FROM public."Phosphosite_table" WHERE "GENE_NAME" LIKE \''"%" + nameFilter +  "%" '\' OR "SYNONYMS" LIKE  \'' "%" + nameFilter +  "%" '\''
    data4 = db.Phospho(phosphosite)
    return render_template('kinase/results.html', data=data, data2=data2, data3=data3, data4=data4) 
    #except:
      #  return render_template ('kinase/error.html')

@kinase_blueprint.route('/inhib_info/')
def inhib_info():
    query = 'SELECT * FROM public."Inhibitor_table"  WHERE "INHIBITOR_NAME" LIKE \'' "%" + data2 +  "%" '\''
    data = db.Query(query)
    return render_template('inhibitor/results.html', data=data) 

templates/analysis/index.html
{% extends "menu.html" %}
{% block content %}
<div class="container" align="center">
	
<form name="file" action= {{ url_for('analysis.upload') }} method="POST" enctype="multipart/form-data">
	<!-- COMPONENT START -->
	<div class="form">
      <label for="exampleFormControlFile1"><h1>Proteomics File browser</h1></label>

		<div class="input-group input-file" name="file">
    		<input type="file" name="file" class="form-control" accept=".tsv" multiple/>			
            <span class="input-group-btn" >
        
    		</span>

		</div>
	</div>
	<!-- COMPONENT END -->
	<div class="form-group btn-group">
		
		<button type="submit" name="file" value="file" class="btn btn-primary">GO!</button>
		<button type="reset" class="btn btn-danger pull-right">Reset</button>
	</div>
</form>
</div>
</div>
</div>


{% endblock %}

templates/analysis/results.html
{% extends "menu.html" %}
{% block content %}

<div class="container" align="center">

<h1> Your Results! </h1>
<p> Here is your file result: 
        {% for table in tables %}
        {{ table|safe }}
    </p>

    <img src="{{url_for('static', filename=ourprecious)}}" alt="Your results can't be displayed. Bad luck">

    {% endfor %}

<p> Please click on the button below to save your full results to your computer </p>

<form method="GET" action= {{url_for('analysis.download_all') }} >
<button type="submit" name= "Download" class="btn btn-success btn-lg">Download Files</button>
</form>
</div>

{% endblock %}

templates/analysis/uploadedfile.html
{% extends "menu.html" %}
{% block content %}
<div class="container" align="center">

<h1> Upload Successful! </h1>
<p>Please give us a moment until we analise the file you uploaded </p>

</div>
{% endblock %}

templates/index.html
{% extends "menu.html" %} {% block content %}
<title>Home</title>
<!-- Set jumbotron for homepage -->
<div class="container" align="center">
  <div class="jumbotron text-center well background:#27A967;color: white;">
    <h1>Kellerman Kinase Database</h1> 
      <p>Kellerman Kinase is a searable, extensive database including all known human kinases. </p> 
  </div>
  <!-- Apply bootsraps grid and glyphicon symbols -->
  <div class="row">
      <div class="col-sm-6">
        <span class="glyphicon glyphicon-search"></span> 
          <p> Search our <a href="{{ url_for('kinase.index') }}">kinase </a>
            and <a href="{{ url_for('inhibitor.index') }}">inhibitor</a> database 
            to find rescources for our research. Our database covers general and 
            phosopsihte information on all known kinases and their related inhibitors.
          </p> 
      </div>
          <div class="col-sm-6">
              <span class="glyphicon glyphicon-upload"></span>
              <span class="glyphicon glyphicon-download"></span>
          <p>Upload your phosphoporteomics data on our <a href="{{ url_for('analysis.index') }}">analysis</a> page and download your results file.
            Our database will calculate the pecentage foldchange of your data. 
          </p>   
        </div>
  </div>

{% endblock %}

templates/inhibitor/index.html
{% extends "menu.html" %} {% block content %}
<title>Inhibitors</title>

<!-- Request form for inhibitor search box -->
<div class="container" align="center">
<h1>Search Inhibitors</h1>
<div class="search-container">
  <form action="{{ url_for('inhibitor.index') }}", method = "post">
      <input type="text" placeholder="Search Inhibitors... " name="name">
        <button type="submit" class="btn btn-primary" >GO!</button>
        </div>
    </form>
</div>
{% endblock %}

templates/inhibitor/results.html
{% extends "menu.html" %} {% block content %}
<title>Inhibitors Results</title>
<div class="container">

<!-- Start for loop for inhibitor data variable -->
{% for item in data %}
<h2>{{item[0]}}</h2>
<table>
    <tr>
        <td>Chemical Strucutre: {{item[1]}}</td>
    </tr>
    <tr>
        <td>Molecular weight: {{item[2]}}</td>
    </tr>
    <tr><td>Action: {{item[4]}}</td></tr>
    <tr><td>Inchl key: {{item[5]}}</td></tr>
    <tr><td>Pubchem id: {{item[6]}}</td></tr>
    <tr><td>Smiles: {{item[7]}}</td></tr>
</table>

{% endfor %}

</div>
{% endblock %}

templates/kinase/error.html
{% extends "menu.html" %} {% block content %}
<div class="container">
<title>Error! </title>
<h3>Sorry! There is no information for that kinase. </h3>
<p><b><a href="{{ url_for('kinase.index') }}">Click here to search again. </a></b></p>
</div>
{% endblock %}

templates/kinase/index.html
{% extends "menu.html" %} {% block content %}
<title>Kinases</title>
<!-- Creat request form for kinase search -->
<div class="container" align="center">
<h1>Search Kinase</h1>
	<form action="{{ url_for('kinase.index') }}", method = "post">
		<input type="text" placeholder="Enter kianse name..." name="name">
		<button type="submit" class="btn btn-primary">GO!</button>
	</form>
</div>

{% endblock %}

templates/kinase/results.html
{% extends "menu.html" %} {% block content %}
<div class="container">
<title> Kinase Results </title>
<!-- Loop through kinase data -->
{% for item in data %}
<b><h1 align="center">{{item[2]}}</h1> </b>
<!-- Apply bootstraps -->
<div class="row">
  <div class="col-sm-4">
    <h4>General Information</h4>
    <p>Group : {{item[4]}}</p>
    <p>Family : {{item[5]}}</p> 
    <p>Subfamily : {{item[6]}}</p>
    <p>Chromosome : {{item[11]}}</p>
    <p>Subcellular location : {{item[12]}}</p>
  </div>
  <div class="col-sm-4">
    <h4>Identities</h4>
    <p>Accession Number : {{item[1]}}</p> 
    <p>Entrez ID : {{item[9]}} </p>
    <p>Uniprot ID : {{item[3]}} </p>
  </div>
  <div class="col-sm-4">
    <h4>Known {{item[2]}} Inhibitors</h4>
        <!-- Creat scrollbox for inhibitor list -->
        <div style="width: 333px; height: 180px; overflow:auto;">
        <!-- Loop through data from inhibitor relational table and make a list -->
        {% for item in data2 %}
        <ul><li><a href="{{ url_for('kinase.inhib_info') }}">{{item[0]}}</a></li></ul>
        {% endfor %}
        </div>
  </div>
</div>
<!-- Set phosphosite heading -->
<div class = "row" >
  <div class="col-sm-12">
    <h2 align="center">Phosphosites</h2>
</div></div>
<div class = "row" >
  <div class="col-sm-4">
    <!-- Create table for phosphosite data and apply scrollbox -->
    <h4>Genmoic Location</h4>
      <div style="width: 333px; height: 180px; overflow:auto;">
        <table>
        <th>Phosophosite</th>
        <th> by Kinase</th>
            {% for item in data4 %}
            <tr style="border-bottom: 1px solid #ddd; border-collapse: collapse; padding: 15px;">
            <td> {{item[6]}}</td>
            <td> {{item[7]}}</td>
            </tr>
            {% endfor %}
        </table>
      </div>
  </div>
<div class="col-sm-4">
    <h4>Neighbouring Sequences</h4>
        <p>Protein Sequence: <div style="width: 110px; height: 50px; overflow: auto;"> {{item[7]}}</div> </p>
        <p>Domain Sequece: <div style="width: 110px; height: 50px; overflow: auto;"> {{item[8]}}</div></p>
        {% endfor %}
</div>
<div class="col-sm-4">
  <h4>Target proteins</h4>
  <div style="width: 333px; height: 180px; overflow:auto;">
    <table>
      <th>Target Gene</th>
      <th>Phosopho Site</th>
    
        {% for item in data3 %}
        <tr style="border-bottom: 1px solid #ddd; border-collapse: collapse; padding: 15px;">

          <td> {{item[2]}}</td>
          <td> {{item[6]}}</td>
        </tr>
        {% endfor %}
    </table>
  </div>       
  </div>
     

</div> 
</div>
        
{% endblock %} 

templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Kellerman Kinase</title>
  <!-- accept character set and fit application to different size screens -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- link bootstraps and custom style sheets -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<!-- Split pages into 3 coloums using bootstraps grid -->
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4"></div>
    <div class="col-sm-4"></div>
</div>
<body>
<!-- top nav bar -->
<div class="container-fluid">
    <nav class="navbar navbar-inverse">
        <div class="nav navbar-header">
            <a class="navbar-brand" href="{{url_for('index') }}">Kellerman Kinase </a>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('kinase.index') }}">Kinase</a></li>    
            <li><a href="{{ url_for('inhibitor.index') }}">Inhibitors</a></li>
            <li><a href="{{ url_for('analysis.index') }}">Analysis</a></li>
        </ul>
        </nav>
    </nav>
</div>
{% block content %} {% endblock %}

</body>
</html>